// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AgentTemplate$Type } from "./AgentTemplate";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AgentTemplate"]: AgentTemplate$Type;
    ["contracts/AgentTemplate.sol:AgentTemplate"]: AgentTemplate$Type;
  }
}
