// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { NFTFactory$Type } from "./NFTFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NFTFactory"]: NFTFactory$Type;
    ["contracts/NFTFactory.sol:NFTFactory"]: NFTFactory$Type;
  }
}
