/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentFactory {
  export type AgentInfoStruct = {
    agentAddress: AddressLike;
    templateAddress: AddressLike;
    cid: string;
  };

  export type AgentInfoStructOutput = [
    agentAddress: string,
    templateAddress: string,
    cid: string
  ] & { agentAddress: string; templateAddress: string; cid: string };
}

export interface AgentFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentCounter"
      | "agentTemplate"
      | "agentsByCreator"
      | "createAgent"
      | "getAgentsByCreator"
      | "owner"
      | "renounceOwnership"
      | "setAgentTemplate"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentCreated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentTemplate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentsByCreator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "createAgent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAgentsByCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentTemplate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    agentAddress: AddressLike,
    templateAddress: AddressLike,
    cid: string
  ];
  export type OutputTuple = [
    creator: string,
    agentAddress: string,
    templateAddress: string,
    cid: string
  ];
  export interface OutputObject {
    creator: string;
    agentAddress: string;
    templateAddress: string;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AgentFactory;
  waitForDeployment(): Promise<this>;

  interface: AgentFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentCounter: TypedContractMethod<[], [bigint], "view">;

  agentTemplate: TypedContractMethod<[], [string], "view">;

  agentsByCreator: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string] & {
        agentAddress: string;
        templateAddress: string;
        cid: string;
      }
    ],
    "view"
  >;

  createAgent: TypedContractMethod<[cid: string], [string], "nonpayable">;

  getAgentsByCreator: TypedContractMethod<
    [creator: AddressLike],
    [AgentFactory.AgentInfoStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentTemplate: TypedContractMethod<
    [_agentTemplate: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentTemplate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentsByCreator"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string] & {
        agentAddress: string;
        templateAddress: string;
        cid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgent"
  ): TypedContractMethod<[cid: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentsByCreator"
  ): TypedContractMethod<
    [creator: AddressLike],
    [AgentFactory.AgentInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentTemplate"
  ): TypedContractMethod<[_agentTemplate: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentCreated"
  ): TypedContractEvent<
    AgentCreatedEvent.InputTuple,
    AgentCreatedEvent.OutputTuple,
    AgentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentCreated(address,address,address,string)": TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;
    AgentCreated: TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
