// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Create2$Type } from "./Create2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Create2"]: Create2$Type;
    ["@openzeppelin/contracts/utils/Create2.sol:Create2"]: Create2$Type;
  }
}
