// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AgentFactory$Type } from "./AgentFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AgentFactory"]: AgentFactory$Type;
    ["contracts/AgentFactory.sol:AgentFactory"]: AgentFactory$Type;
  }
}
