// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PayableNFT$Type } from "./PayableNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PayableNFT"]: PayableNFT$Type;
    ["contracts/PayableNFT.sol:PayableNFT"]: PayableNFT$Type;
  }
}
